### ISSUE TITLE
2 errors

### ISSUE THREAD

**Issue by Trylek12** [Emile442/altis-pan#7]
1. I cant change file name to ".env" because windows must have a for example wtf.env (sorry for my eng, I still learn).

2. *     Application In Production!     *
**************************************

Do you really wish to run this command? [y/N] y

  [Illuminate\Database\QueryException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'forge.players' d
  oesn't exist (SQL: alter table `players` add `duredon` int not null, add `t
  imestamp` int not null)

[PDOException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'forge.players' d
  oesn't exist

**Comment by Emile442** [comment]
1. Take your CMD and write ' mv .env.exemple .env '
2. I think it's because you have not define the host, name of database and other settings in .env

**Comment by Trylek12** [comment]
I defined hostname, db, user and pass. Same error

[Illuminate \ Database \ QueryException] 
SQLSTATE [42S02]: Base table or view not found: 1146 Table 'forge.players' d 
oesn't exist (SQL: alter table players add duredon int not null, add t imestamp int not null)

[PDOException] 
SQLSTATE [42S02]: Base table or view not found: 1146 Table 'forge.players' d 
oesn't exist

**Comment by Emile442** [comment]
Are you sure about informations you have field up in `.env` ?

**Comment by Trylek12** [comment]
yes, all tabeles instaled, but i can't find table players, only users.

[Illuminate\Database\QueryException]

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'panel.players' doesn't exist (SQL: alter table `players` add `duredon` int not null, add `timestamp` int not null)         
 
[PDOException]                                                                           
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'panel.players' doesn't 

exist

and SS http://imgur.com/9CIMP6P

**Comment by Emile442** [comment]
OK this is normal, it is because you are not in the database of AltisLife

**Comment by Trylek12** [comment]
aaa ok, thanks. My fail
